FROM ubuntu:20.04

# RUN useradd -ms /bin/bash attaquant

RUN apt-get update;apt-get install iputils-ping -y; apt-get install net-tools -y; apt-get install tcpdump -y; apt-get install arping -y;apt-get install dsniff -y;

WORKDIR /home/attaquant
